NUMPY LIBRARY

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
print('array\n',arr)
print('2d array\n',arr_2d)

array
 [1 2 3]
2d array
 [[1 2 3]
 [4 5 6]]


In [3]:
# Special Arrays
print('zero array',np.zeros((3, 3)))
print('ones array',np.ones((2, 4)))
print('Identity array',np.eye(3))
print('arange array',np.arange(0, 10, 2))
print('linspace array',np.linspace(0, 1, 5))
print('random array',np.random.rand(3, 2))
print('random array',np.random.randn(3, 2))

zero array [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity array [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange array [0 2 4 6 8]
linspace array [0.   0.25 0.5  0.75 1.  ]
random array [[0.74882926 0.21431352]
 [0.00540249 0.86869696]
 [0.06515081 0.3591521 ]]
random array [[ 0.21404709  0.27686575]
 [ 0.38831753 -0.80160421]
 [ 2.94857431  1.49517598]]


In [4]:
#array attributes
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int64
2
6


In [5]:
#array operations
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print('addition',arr1+arr2)
print('subtraction',arr1-arr2)
print('multiplication',arr1*arr2)
print('division',arr1/arr2)
print('sin',np.sin(arr1))


addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]
sin [0.84147098 0.90929743 0.14112001]


In [6]:
#matrix multiplicatioon
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print('matrix multiplication',a.dot(b))
print('matrix multiplication using @',a@b)

matrix multiplication [[19 22]
 [43 50]]
matrix multiplication using @ [[19 22]
 [43 50]]


In [7]:
#aggregation
arr=np.array([[1,2,3],[4,5,6]])
print('sum',arr.sum())
print('min',arr.min())
print('max',arr.max())
print('mean',arr.mean())
print('std',arr.std())

sum 21
min 1
max 6
mean 3.5
std 1.707825127659933


In [8]:
#indexing and slicing
arr=np.array([1,2,3,4,5,6])
print('first element',arr[0])
print('last element',arr[-1])
print('first 3 elements',arr[:3])
print('last 3 elements',arr[-3:]) 
print('every other element',arr[::2])
print('From second element fourth element',arr[1:4])

first element 1
last element 6
first 3 elements [1 2 3]
last 3 elements [4 5 6]
every other element [1 3 5]
From second element fourth element [2 3 4]


In [9]:
#2D array
arr=np.array([[1,2,3],[4,5,6]])
print('first row',arr[0])
print('first element of first row',arr[0,0])
print('first element of second row',arr[1,0])
print('first two rows',arr[:2])
print('first two rows and first two columns',arr[:2,:2])

first row [1 2 3]
first element of first row 1
first element of second row 4
first two rows [[1 2 3]
 [4 5 6]]
first two rows and first two columns [[1 2]
 [4 5]]


In [10]:
#boolean indexing
arr=np.array([1,2,3,4,5,6])
mask=arr>3
print('mask',mask)
print('elements greater than 3',arr[mask])

mask [False False False  True  True  True]
elements greater than 3 [4 5 6]


In [11]:
#reshaping and combining array
arr=np.array([[1,2,3],[4,5,6]])
print('orginal array',arr)
print('reshaped array',arr.reshape(3,2))

orginal array [[1 2 3]
 [4 5 6]]
reshaped array [[1 2]
 [3 4]
 [5 6]]


In [12]:
#concatenation
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print('concatenation',np.concatenate((a,b)))

concatenation [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
#stacking
a=np.array([1,2])
b=np.array([3,4])
print('vertical stacking',np.vstack((a,b)))
print('horizontal stacking',np.hstack((a,b)))

vertical stacking [[1 2]
 [3 4]]
horizontal stacking [1 2 3 4]


In [14]:
#broadcasing
a=np.array([1,2,3])
a+5

array([6, 7, 8])

In [15]:
#saving and loading a file
a=np.array([[1,2,3],[4,5,6]])
np.save('array.npy',a)
b=np.load('array.npy')
print(b)

[[1 2 3]
 [4 5 6]]
